# Generated by Django 4.2.5 on 2023-10-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
    ]
