# Generated by Django 4.2.5 on 2023-11-04 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231009_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('star', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roundstat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.DeleteModel(
            name='GameStat',
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
        migrations.DeleteModel(
            name='RoundStat',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
